### ISSUE TITLE
Associated API call that generates the QR Code?

### ISSUE THREAD

**Issue by iadj** [jusleg/snaptag#1]
I'm looking to host the generation part of the Snaptag generator on my own server to guarantee uptime. How is the Snapcode generated server-side? The one called in the following URL: 

```
https://feelinsonice-hrd.appspot.com/web/deeplink/snapcode?username=".$username."&type=SVG&size=".$size;
```

**Comment by jusleg** [comment]
Hi,
Do you want to generate the whole snaptag server-side or use part of the client side. I split my code into two parts. The backend gets the svg image directly from snapchat. It then adds the necessary tag to allow for CSS manipulation. Here is the PHP code https://gist.github.com/jusleg/9c2604dc1171df6c78a119077ae75f4c
Then I use Javascript to modify the colors in the front end using sliders. Here is a demo using HSL slider and image. http://jusleg.com/snapcode The conversion from svg to png is done in the front end using canvas. You can find the method drawCanvas in the backbone.js file. I hope this clears some things up.

**Comment by iadj** [comment]
Hey @jusleg 
I was interested in what the following URL does:

```
            $url = "https://feelinsonice-hrd.appspot.com/web/deeplink/snapcode?username=".$username."&type=SVG&size=".$size;
```

But as I understand it, this is a URL belonging to Snapchat? I was thinking perhaps it was possible to generate the actual QR code on our own server, but it seems that the appspot URL is necessary to do this.

**Comment by jusleg** [comment]
Hi @iadj 
The url belongs to Snapchat. I do not know how their code works and I do not have access to the source. I am only getting the qrcode in svg format and then I add the necessary tag to allow for CSS modification.
