### ISSUE TITLE
Snaptag image is broken

### ISSUE THREAD

**Issue by sukhwinderkaur** [jusleg/snaptag#5]
Hey @jusleg 

I have implemented the functionality to add pictures in ghost but when I am trying to download the same snapcode img is showing as broken image icon. Please help me to get it solve ASAP.

Here is the downloaded snaptag image with the broken image tag.
![snaptag 12](https://user-images.githubusercontent.com/22677952/32482836-7963eca6-c3bf-11e7-9435-bf07a2eea89b.png)

**Comment by jusleg** [comment]
Did you try on https://snapcodes.herokuapp.com/ with the same image? If so, what are the results?

**Comment by jusleg** [comment]
The code was not implemented to download with the picture in it. I'll try to look into it.

**Comment by sukhwinderkaur** [comment]
@jusleg 
When can I expect to get the code to download snap-tag with the picture? Actually, I really need this for today and I will thankful to you for your this help.

Please help me :(

**Comment by jusleg** [comment]
Closing for now as downloading snaptag with images is not a feature currently supported by snaptag.
