### ISSUE TITLE
Heroku API doesn't exist

### ISSUE THREAD

**Issue by Hackinet** [jusleg/snaptag#8]
API Endpoint: `https://snapcodes.herokuapp.com/`

![image](https://user-images.githubusercontent.com/11132005/80453849-aeb47700-8946-11ea-807a-b4a0e6a63b93.png)

Error in file `backbone.js` in function `fill()` on `line 19`

![image](https://user-images.githubusercontent.com/11132005/80454025-ff2bd480-8946-11ea-810d-4b95b6a2ea19.png)

**Comment by jusleg** [comment]
people still used it? I'll get it back up.

**Comment by jusleg** [comment]
It's back up
